### ISSUE TITLE
Add Chinese Translation

### ISSUE THREAD

**Issue by KevienJohnson** [GrinPlusPlus/GrinPlusPlusMobile#19]
[AppResources.zh-CHT.resx.txt](https://github.com/GrinPlusPlus/GrinPlusPlusMobile/files/7832887/AppResources.zh-CHT.resx.txt)
[AppResources.zh-CN.resx.txt](https://github.com/GrinPlusPlus/GrinPlusPlusMobile/files/7832888/AppResources.zh-CN.resx.txt)
[AppResources.zh-HK.resx.txt](https://github.com/GrinPlusPlus/GrinPlusPlusMobile/files/7832889/AppResources.zh-HK.resx.txt)

**Comment by davidtavarez** [comment]
I just added them! Thanks! https://github.com/GrinPlusPlus/GrinPlusPlusMobile/commit/923b0b8b8a698c2a5eb1b716bf5f3e619297a45e

**Comment by KevienJohnson** [comment]
Hello, the contents of the "AppResources.zh-Hans.resx" and "AppResources.zh-Hant.resx" files you added are reversed.

**Comment by KevienJohnson** [comment]
> I just added them! Thanks! [923b0b8](https://github.com/GrinPlusPlus/GrinPlusPlusMobile/commit/923b0b8b8a698c2a5eb1b716bf5f3e619297a45e)
 
Hello, the contents of the "AppResources.zh-Hans.resx" and "AppResources.zh-Hant.resx" files you added are reversed.

**Comment by davidtavarez** [comment]
My bad!

**Comment by davidtavarez** [comment]
Check again please https://github.com/GrinPlusPlus/GrinPlusPlusMobile/tree/v0.3.0/GrinPlusPlus/GrinPlusPlus/Resources
