### ISSUE TITLE
User interface is not alligned

### ISSUE THREAD

**Issue by zelva1** [GrinPlusPlus/GrinPlusPlusMobile#2]
I am using Oneplus 3, running on android version 9. [https://prnt.sc/w5krti](url) I posted the link how I see it.

**Comment by davidtavarez** [comment]
thank you for reporting

**Comment by cmck-xyz** [comment]
Can confirm same issue on Huawei P10 (Android 9.1)
![image](https://user-images.githubusercontent.com/573177/107127555-2b518a00-68b7-11eb-9f14-64ad8278e4ae.png)
