### ISSUE TITLE
When the Node is offline, redirect user to an Action Screen 

### ISSUE THREAD

**Issue by davidtavarez** [GrinPlusPlus/GrinPlusPlusMobile#5]
The user should be able to start the node from the action screen.

**Comment by mojitoo** [comment]
what do you mean by action screen ? is it the first loading screen ?
my idea was to add « START » ,  « re-sync » and « stop » to the NODE loading screen. but also keep it on the dropdown notification menu.

**Comment by davidtavarez** [comment]
> what do you mean by action screen ? is it the first loading screen ?
> my idea was to add « START » ,  « re-sync » and « stop » to the NODE loading screen. but also keep it on the dropdown notification menu.

You just described the Action Screen.
